# Generated by Django 4.1.1 on 2022-09-17 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estoque',
            options={'ordering': ('created',)},
        ),
        migrations.AlterField(
            model_name='estoque',
            name='movimento',
            field=models.CharField(choices=[('e', 'Entrada'), ('s', 'Saída')], max_length=1),
        ),
        migrations.AlterField(
            model_name='estoqueitens',
            name='estoque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estoques', to='estoque.estoque'),
        ),
    ]
